version: '3'

networks:
  vine:

volumes:
  mysql_data:

services:
  app:
    build: .docker
    container_name: vine
    restart: always
    working_dir: /var/www/html
    depends_on:
      # - mysql
      - nginx
    volumes:
      - .:/var/www/html
    networks:
      - vine

  nginx:
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vine

  # mysql:
  #   image: mariadb:latest
  #   ports:
  #     - 3307:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_DATABASE: '${DB_DATABASE}'
  #     MYSQL_USER: '${DB_USERNAME}'
  #     MYSQL_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - vine
