version: '3.8'

services:
  app:
    build: .docker
    container_name: vine
    restart: always
    working_dir: /var/www/html
    depends_on:
      - nginx
      - db
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: vine
      POSTGRES_USER: vine
      POSTGRES_PASSWORD: vine
